GET http://localhost:3000/

#Host: http://localhost:3000


###

GET /authorize
Host: auth.delta.nitt.edu

{
    "client_id": "ajaNYGBqSLCeAcvm",
    "redirect_uri": "http%3A%2F%2Flocalhost%3A3000%2Fauthenticated"
}

###
POST /
Host: localhost:3000
Content-Type: application/json

{
    "username": "test"
}

###
POST /api/oauth/token HTTP/1.1
Host: auth.delta.nitt.edu
Content-Type: application/x-www-form-urlencoded

{
    "client_id": "ajaNYGBqSLCeAcvm",
    "client_secret": "pp181oQ444EOTGAMeJpc8UmfWWKti1Wx",	
    "grant_type": "authorization_code",	
    "code": "722df97d413e8c3cfbbf41c8e09bbd2215cfb35a",
    "redirect_uri": "http%3A%2F%2Flocalhost%3A3000%2Fauthenticated%2F"
}
###
GET /api/oauth/oidc/key HTTP/1.1
Host: auth.delta.nitt.edu

###
POST /user HTTP/1.1
Host: auth.delta.nitt.edu/api/resources/
Authorization: Bearer 02f71255ee95a04d6066de3969bb52f466c90572

###
GET /api/v3/files/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
HOST: www.virustotal.com
x-apikey: